# Generated by Django 2.1.2 on 2019-01-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.IntegerField()),
                ('con', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='debate',
            name='hash',
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='pfp',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=12),
        ),
        migrations.AddField(
            model_name='debate',
            name='pfp',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='side',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='debate',
            name='date',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=10),
        ),
        migrations.AlterField(
            model_name='debate',
            name='genre',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='debate',
            name='picture',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='debate',
            name='title',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='debate',
            name='username',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='voting',
            name='debate2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.Debate'),
        ),
        migrations.AddField(
            model_name='likes',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.Comments'),
        ),
    ]
