# Generated by Django 2.1.2 on 2019-02-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0003_auto_20190131_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='picture',
        ),
    ]
