# Generated by Django 2.1.2 on 2019-04-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0010_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
